apiVersion: apps/v1
kind: Deployment
metadata:
  name: catechization-client-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: catechization-client
    spec:
      containers:
        - name: catechization-client
          image: deshmukhp/catechization-client
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http-port
  selector:
    matchLabels:
      app: catechization-client
